# Generated by Django 3.0.3 on 2020-03-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coronavirus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(default=0, upload_to='photos'),
            preserve_default=False,
        ),
    ]
